# Generated by Django 3.1.2 on 2020-10-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('signature', models.TextField()),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('signature', models.TextField()),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRead', models.DateTimeField(null=True)),
                ('dateSent', models.DateTimeField(null=True)),
                ('dateReceived', models.DateTimeField(auto_now_add=True)),
                ('video', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('audio', models.CharField(max_length=300)),
                ('thumbnailURL', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('receipent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribes_core.person')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribes_core.subscriptionperson')),
            ],
        ),
    ]
