# Generated by Django 3.1.2 on 2020-10-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribes_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='signature',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='subscriptionperson',
            old_name='signature',
            new_name='identifier',
        ),
    ]
