# Generated by Django 3.1.2 on 2020-10-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tribes_core', '0002_auto_20201017_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(null=True)),
                ('audio', models.CharField(max_length=200, null=True)),
                ('thumbnailURL', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thumbnailURL',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
        migrations.AddField(
            model_name='message',
            name='messageAttachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribes_core.post'),
        ),
    ]
