# Generated by Django 3.1.2 on 2020-12-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes_core', '0005_auto_20201213_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
